# for the API

apiVersion: apps/v1
kind: Deployment
metadata:
  name:  opbox-api
  namespace: stagging
  labels:
    app:  api
spec:
  selector:
    matchLabels: 
      app: api
  replicas: 1
  template:
    metadata:
      labels:
        app:  api
    spec:
      containers:
      - image:  registry.gitlab.com/ubox-group/ubox-api-src:29cb4e08 #specify latest image built automatically from pipe
        name:  apicontainer    
        ports:
        - containerPort:  3030
          name:  apiport
        volumeMounts:
        - mountPath: /usr/src/app/back/node_modules
          name: api-data
      restartPolicy: Always
      volumes:
        - name:  api-data
          persistentVolumeClaim: 
            claimName: api-pvc
--- 

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-pvc
  namespace: stagging
spec:
  accessModes: 
   - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: my-api-local-storage
  volumeName: api-pv
---

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: my-api-local-storage
  namespace: stagging
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: api-pv
  namespace: stagging
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: my-api-local-storage
  local:
    path: /data/stagging/api
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - node2
          - node3


